# Site settings
name: Haijiang's Blog
email: haijiang_xu@qq.com
author: Haijiang Xu
github: https://github.com/xuhaijiang/
baseurl: ""
description: Just Record。
meta_description: 个人博客;
motto: 认识你自己。
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: xuhaijiang

# Build settings
markdown: kramdown

# baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

